[OPP-1518] Fjerne bruk av ISSO fra modiapersonoversikt-api
navikt/modiapersonoversikt-api pull request #1029
Opened 2022-11-29 13:14 UTC by Jesperpaulsen

2022-11-29 13:55 UTC, abrhanav approved these changes

2022-12-01 09:18 UTC, nutgaard requested changes
Kan vi skal undersøke hvorfor vi måtte legge til ekstra headere i pdlservice'n? 🤔

2022-12-01 09:18 UTC, nutgaard commented on web/src/main/java/no/nav/modiapersonoversikt/service/pdl/PdlOppslagServiceImpl.kt
> +        header(AUTHORIZATION, AUTH_METHOD_BEARER + AUTH_SEPERATOR + oboTokenClient.exchangeOnBehalfOfToken(azureToken))
Nav-callId headeren skal bli automatisk lagt på av `LogginGraphqlClient` 🤔 Så burde egentlig ikke være behov for å legge til den?

2022-12-01 09:18 UTC, nutgaard commented on web/src/main/java/no/nav/modiapersonoversikt/infrastructure/AuthContextUtils.kt
> +    fun requireBoundedOboToken(oboTokenProvider: BoundedOnBehalfOfTokenClient): String {
[NITPICK] metode navnet blir litt "off" her. En token-client er "bounded" til ett scope (annen app), men å si bounded-obo-token blir liksom litt smør-på-flesk.

2022-12-02 10:33 UTC, nutgaard approved these changes

2022-12-02 11:08 UTC, merged