[OPP-1153] hente ut person med vegemål/fullmakt fra pdl
navikt/modiapersonoversikt-api pull request #263
Opened 2021-02-10 14:20 UTC by vildestefferud

2021-02-17 13:39 UTC, nutgaard commented on api/src/main/resources/pdl/queries/hentPersonVergemaalEllerFullmakt.graphql
> +            metadata {
Bruker vi alle informasjonselementene vi henter ut?

2021-02-17 13:42 UTC, nutgaard commented on kjerneinfo/kjerneinfo-consumer/src/main/java/no/nav/kjerneinfo/consumer/fim/person/vergemal/PdlVergemalService.kt
> +        val vergeIdenter: List<String> = pdl.hentPersonVergemaalEllerFullmakt(fodselsnummer)
Vi kaller `pdl.hentPersonVergemaalEllerFullmakt` via `hentVergemalFraPdl` også. Kan vi bare gjenbruke responsen derifra?

2021-02-17 13:43 UTC, nutgaard commented on kjerneinfo/kjerneinfo-consumer/src/main/java/no/nav/kjerneinfo/consumer/fim/person/vergemal/PdlVergemalService.kt
> +                .map { verge: HentPersonVergemaalEllerFullmakt.VergemaalEllerFremtidsfullmakt? -> getIdentFromVerge(verge?.vergeEllerFullmektig) }
Tror ikke vi trenger `?` her siden `pdl.hentPersonVergemaalEllerFullmakt` returnerer en liste uten `null`

2021-02-17 13:45 UTC, nutgaard commented on kjerneinfo/kjerneinfo-consumer/src/main/java/no/nav/kjerneinfo/consumer/fim/person/vergemal/PdlVergemalService.kt
> +        val vergeNavn = pdl.hentNavnBolk(vergeIdenter)
Vi har også navn i `hentPersonVergemaalEllerFullmakt.graphql`, kan vi bruke det? Eller er det noe annet?

2021-02-17 13:45 UTC, nutgaard commented on kjerneinfo/kjerneinfo-consumer/src/main/java/no/nav/kjerneinfo/consumer/fim/person/vergemal/PdlVergemalService.kt
> +                .toList()
`.stream()` og `.toList()` kan vi slippe unna her

2021-02-17 13:47 UTC, nutgaard commented on kjerneinfo/kjerneinfo-consumer/src/main/java/no/nav/kjerneinfo/consumer/fim/person/vergemal/PdlVergemalService.kt
> +            if (ident == PDL_VERGES_FNR_MANGLENDE_DATA) null else ident
er `00000000000` noe vi også kan få fra pdl, eller var det noe tps-spesifikt?

2021-02-17 13:55 UTC, nutgaard commented on kjerneinfo/kjerneinfo-consumer/src/main/java/no/nav/kjerneinfo/consumer/fim/person/vergemal/domain/PdlVerge.kt
> +    fun getIdent(): String? {
Kotlin lager automatisk getter/setter metoder for oss, så vi kan kanskje greie å kvitte oss med disse her.

2021-02-17 13:55 UTC, nutgaard commented on kjerneinfo/kjerneinfo-consumer/src/main/java/no/nav/kjerneinfo/consumer/fim/person/vergemal/domain/PdlVerge.kt
> +        private val ident: String?,
Vi kan gjerne ta en titt på hvilke av disse feltene som kan være `null` slik at vi får forbedret typesikkerheten våres.

2021-02-17 13:55 UTC, nutgaard commented on kjerneinfo/kjerneinfo-consumer/src/test/java/no/nav/kjerneinfo/consumer/fim/person/vergemal/PdlVergemalServiceTest.kt
> +    @DisplayName("Med vergemål med ufullstendig data")
Siden vi kan skrive fine funksjonsnavn i kotlin, så kan vi sikkert fjerne `@DisplayName`

2021-02-17 13:57 UTC, nutgaard requested changes
Bra jobba. :+1: 
La til noen kommentarer som vi kan titte på sammen om du vil. Går for det meste på at vi i kotlin kan gjøre ting litt enklere i noen tilfeller. :)

2021-02-17 14:01 UTC, tadeankur reviewed
`PdlVergemalService` utdyper ikke om hva den gjør egentlig. Kanskje bytte navn til `PdlVergemalGateway`
https://martinfowler.com/eaaCatalog/gateway.html

2021-02-17 14:03 UTC, tadeankur commented
`VergemalService` har flere methoder som tilhører til `Verge` kan flyttes til `Verge` domain class

2021-02-17 14:10 UTC, tadeankur commented
Hvorfor har vi valgt å bruke `XMLGregorianCalendar` her for `Period`

2021-02-17 14:49 UTC, vildestefferud commented on kjerneinfo/kjerneinfo-consumer/src/main/java/no/nav/kjerneinfo/consumer/fim/person/vergemal/PdlVergemalService.kt
> +            if (ident == PDL_VERGES_FNR_MANGLENDE_DATA) null else ident
Venter på tilbakemelding fra pdl

2021-02-18 09:44 UTC, nutgaard commented on api/src/main/resources/pdl/queries/hentPersonVergemaalEllerFullmakt.graphql
> +                omfangetErInnenPersonligOmraade
`omfangetErInnenPersonligOmraade` tror jeg ikke vi bruker

2021-02-18 09:45 UTC, nutgaard commented on api/src/main/resources/pdl/queries/hentPersonVergemaalEllerFullmakt.graphql
> +            metadata {
Tror ikke vi bruker metadata?

2021-02-18 13:15 UTC, closed without merging