Fix nullpointer
navikt/modiapersonoversikt-api pull request #268
Opened 2021-02-12 16:07 UTC by tadeankur

2021-02-12 16:12 UTC, tadeankur commented
Jeg har testet med flere FNR som feilet i dag i Q0 go ser ut til fungerer fint.

2021-02-15 12:40 UTC, nutgaard requested changes
Tror det er nyttig med en test her også, bare sånn at vi ikke innfører denne feilen i fremtiden.

2021-02-15 12:40 UTC, nutgaard commented on consumer/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/consumer/service/saker/mediation/SakApiGateway.kt
> +    val applikasjon: String = "", //example: IT01 Kode for applikasjon iht. felles kodeverk
Dette vil skape en gi oss `MissingKotlinParameterException` ved deserialisering av `{ "applikasjon": null }` til `SakDto`.

2021-02-17 07:22 UTC, nutgaard approved these changes
LGTM

Legg gjerne til en test for dette slik at vi ikke reintroduserer dette ved ett uhell senere.

2021-02-17 11:12 UTC, nutgaard approved these changes

2021-02-17 11:22 UTC, merged