Opp 1328 saksoversikt
navikt/modiapersonoversikt-api pull request #292
Opened 2021-03-23 10:35 UTC by tadeankur

2021-03-23 10:53 UTC, nutgaard commented on .nais/nais-q0.yml
>      - name: VIRKSOMHET_SAK_V1_SECURITYTOKEN
Vi kan vel slette `VIRKSOMHET_SAK_V1_SECURITYTOKEN` og `VIRKSOMHET_SAK_V1_WSDLURL` også?

2021-03-23 10:57 UTC, nutgaard commented on saksoversikt/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/sak/providerdomain/Baksystem.java
> +    GSAK, PESYS, SAK_OG_BEHANDLING, JOARK, HENVENDELSE, KODEVERK, SAF, SAK
Er vi sikre på at disse feltene kan slettes? At de ikke brukes via reflection, eller deserialisering av data fra ett annet sted?

2021-03-23 10:59 UTC, nutgaard commented on saksoversikt/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/sak/service/SaksService.java
> +                                    .withBaksystem(GSAK)
Burde baksystem være `SAK` her også?

2021-03-23 10:59 UTC, nutgaard commented on saksoversikt/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/sak/service/SaksService.java
> +            feilendeBaksystemer.add(SAK);
Burde vi være konsekvente med bruken av `GSAK`  vs `SAK` ?

2021-03-23 11:00 UTC, nutgaard requested changes
Litt mer som kan fjernes, også er det greit om vi titter på de `Baksystem` greiene

2021-03-23 13:26 UTC, tadeankur commented on saksoversikt/src/main/java/no/nav/sbl/dialogarena/modiabrukerdialog/sak/providerdomain/Baksystem.java
> +    GSAK, PESYS, SAK_OG_BEHANDLING, JOARK, HENVENDELSE, KODEVERK, SAF, SAK
Intellij peker at disse er ikke i bruk. Men ruller tilbake den endring. Har ikke selv god kontroll på den koden

2021-03-24 09:20 UTC, nutgaard commented on .github/workflows/deploy_branch.yml
> +  isDeploy: true
Denne bør vel holdes til false?

2021-03-24 09:24 UTC, nutgaard approved these changes

2021-03-24 10:48 UTC, merged