[OPP-1383] hente riktig kodeverk verdi
navikt/modiapersonoversikt-api pull request #520
Opened 2021-11-19 14:43 UTC by eirikdahlen

Valuta og Landkode har ikke feltene kodeRef, men kodeverksRef.

Knyttet til feil i loggene:
Vi får følgende respons fra Soap: `<landkode>ESP</landkode>`
Og feilmelding:
`bankkonto.bankkontoUtland.landkode.kodeRef must not be null`

2021-11-19 15:16 UTC, eirikdahlen reviewed
`Response message does not contain WS-Addressing properties.  Not correlating response.`
Betyr det at vi burde slenge på `Informasjonsbehov.ADRESSE` også 🤔

2021-11-19 16:30 UTC, nutgaard commented on web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataFletter.kt
> +                                bankkonto.bankkontoUtland.landkode.kodeverksRef
Dette vil være en referanse til kodeverket, så tror ikke dette vil bli riktig. :/

2021-11-19 16:38 UTC, nutgaard requested changes
Tror det er feil felt.

Mtp WS-adressing så er det en SOAP-advarsel, så det er ikke påvirket av hva vi henter ut.
Om det skal tittes på så er det sannsynligvis oppsettet av wsdl'en til PersonV3 eller hvordan vi oppretter CXFClienten

2021-11-22 13:03 UTC, nutgaard approved these changes

2021-11-23 14:49 UTC, nutgaard approved these changes

2021-11-23 15:03 UTC, merged