[OPP-1498] Filtrerer vekk gt som mangler bydel
navikt/modiapersonoversikt-api pull request #862
Opened 2022-08-29 11:55 UTC by vildestefferud

2022-08-29 12:34 UTC, nutgaard commented on tjenestespesifikasjoner/saf-api/src/main/resources/saf/schema.graphql
> +    DPVT
Disse endringene skal vel ikke være med?

2022-08-29 12:57 UTC, nutgaard commented on web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataService.kt
> +    }
Kan kanskje forenkles til noe alà;
```suggestion
    val GT_SOM_BURDE_HA_BYDEL = listOf("0301", "4601", "5001", "1103")
    fun erGyldigGT(gt: String?): Boolean {
        return when {
          gt == null -> false
          GT_SOM_BURDE_HA_BYDEL.contains(gt) -> false
          else -> true
        }
    }
```

2022-08-29 13:13 UTC, nutgaard commented on web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataService.kt
> +        return if (erGyldigGT(gt)) {
For å slippe å iterere over `adressebeskyttelse` kan sjekken flyttes høyere opp.

F.eks kan man utvide `PersondataResult` med en funksjon alà `fun <S> flatMap(block: (t: PersondataResult<T>) -> PersondataResult<S>): PersondataResult<S>` og deretter bruke den.

```kotlin
        val gt: String = geografiskeTilknytning
            .flatMap {
                if (erGyldigGT(it.getOrNull())) {
                    it
                } else {
                    PersondataResult.NotRelevant()
                }
            }
            .fold(
                onSuccess = { it ?: "" },
                onNotRelevant = { null },
                onFailure = { _, _ -> "" }
            ) ?: return PersondataResult.NotRelevant()
```

2022-08-30 08:40 UTC, nutgaard commented on web/src/main/java/no/nav/modiapersonoversikt/rest/persondata/PersondataResult.kt
> +            is Success<T> -> block(this.value as PersondataResult<T>)
Denne castingen vil feile siden `this.value` vil ha typen `T`

Vil sannsynligvis ha noe alà;
```kotlin
is Success<T> -> block(this)
```

2022-08-30 08:41 UTC, nutgaard requested changes
Se egen kommentar

2022-08-30 09:33 UTC, nutgaard submitted a review, later dismissed

2022-08-31 12:42 UTC, eirikdahlen approved these changes

2022-09-01 06:38 UTC, merged