[OPP-1506] Oppgradere github workflows
navikt/modiapersonoversikt-api pull request #973
Opened 2022-11-02 10:58 UTC by abrhanav

2022-11-02 13:45 UTC, nutgaard commented on .github/workflows/main.yml
> +          distribution: 'zulu'
Tror de fleste andre på huset bruker `temurin` her

2022-11-02 13:46 UTC, nutgaard requested changes
Vi må titte på hvilken java distro vi bruker

2022-11-03 13:50 UTC, Jesperpaulsen reviewed
LGTM

2022-11-03 13:51 UTC, Jesperpaulsen approved these changes
LGTM

2022-11-03 13:51 UTC, nutgaard approved these changes

2022-11-03 13:54 UTC, merged